spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/yourdatabase
#    username: yourusername
#    password: yourpassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
application:
  keys:
    api: ${API_KEY}
    client-secret: ${CLIENT_SECRET}
  uris:
    token: https://testapi.mehrwerk.de/v2/iam/oauth/token
    shops: https://testapi.mehrwerk.de/v3/cashback/shops
logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG
